/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Recepcion;

import forms_pacientes.FrmPacient;
import forms_profecionales.FrmLocation;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import miselaneos.GUI;
import miselaneos.Iconos;
import miselaneos.Imagenes;
import miselaneos.JDeskTopSis;

/**
 *
 * @author kusse
 */
public class FrmSistema extends javax.swing.JFrame {
    
    public static Iconos iconos = new Iconos(); //Declaro public para poder acceder luego desde cualquier lugar del proyecto en cualquier objeto.
    public static Imagenes imgs = new Imagenes(); //Lo misma que en la anterior public.
    
    private GUI gui;

    /**
     * Creates new form FrmSistema
     */
    public FrmSistema() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        gui = new GUI();
    }
    
    
    
    private void loadLocation(){
         gui.loadLocation(FrmLocation.id, true);
    }
    
    private void loadClients(){
         gui.loadClients(FrmPacient.id, true);
    }
    
    private void salirSistema() {
        if(JOptionPane.showConfirmDialog(null, "Desea salir del Sistema por Completo", "Atención!!!", 
                JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDeskTopSis = new miselaneos.JDeskTopSis();
        jToolBarButtons = new javax.swing.JToolBar();
        btnLocation = new botones.BtnLocation();
        btnClient = new botones.BtnClient();
        btnExit1 = new botones.BtnExit();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuArchivos = new javax.swing.JMenu();
        jMenuLocation = new javax.swing.JMenuItem();
        jMenuClients = new javax.swing.JMenuItem();
        jMenuSalir = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Comercio");
        setIconImage(iconos.getSys(16).getImage()
        );

        jDeskTopSis.setPreferredSize(new java.awt.Dimension(1024, 800));
        getContentPane().add(jDeskTopSis, java.awt.BorderLayout.CENTER);

        jToolBarButtons.setRollover(true);

        btnLocation.setText("");
        btnLocation.setFocusable(false);
        btnLocation.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLocation.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLocationActionPerformed(evt);
            }
        });
        jToolBarButtons.add(btnLocation);

        btnClient.setText("");
        btnClient.setFocusable(false);
        btnClient.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnClient.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientActionPerformed(evt);
            }
        });
        jToolBarButtons.add(btnClient);

        btnExit1.setText("");
        btnExit1.setFocusable(false);
        btnExit1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExit1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnExit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExit1ActionPerformed(evt);
            }
        });
        jToolBarButtons.add(btnExit1);

        getContentPane().add(jToolBarButtons, java.awt.BorderLayout.NORTH);

        jMenuArchivos.setText("Archivo");
        jMenuArchivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuArchivosActionPerformed(evt);
            }
        });

        jMenuLocation.setIcon(iconos.getLocation(16));
        jMenuLocation.setText("Localidades");
        jMenuLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuLocationActionPerformed(evt);
            }
        });
        jMenuArchivos.add(jMenuLocation);

        jMenuClients.setIcon(iconos.getClient(16)
        );
        jMenuClients.setText("clientes");
        jMenuArchivos.add(jMenuClients);

        jMenuBar1.add(jMenuArchivos);

        jMenuSalir.setText("Salir");

        jMenuItem3.setIcon(iconos.getExit(16)
        );
        jMenuItem3.setText("Salir del Sistema");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenuSalir.add(jMenuItem3);

        jMenuBar1.add(jMenuSalir);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        salirSistema();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void btnLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLocationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLocationActionPerformed

    private void btnExit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExit1ActionPerformed
        salirSistema();
    }//GEN-LAST:event_btnExit1ActionPerformed

    private void jMenuArchivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuArchivosActionPerformed
       loadClients();
    }//GEN-LAST:event_jMenuArchivosActionPerformed

    private void jMenuLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuLocationActionPerformed

       loadLocation();    
    }//GEN-LAST:event_jMenuLocationActionPerformed

    private void btnClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientActionPerformed
        loadClients();
    }//GEN-LAST:event_btnClientActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmSistema().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private botones.BtnClient btnClient;
    private botones.BtnExit btnExit1;
    private botones.BtnLocation btnLocation;
    public static miselaneos.JDeskTopSis jDeskTopSis;
    private javax.swing.JMenu jMenuArchivos;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuClients;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuLocation;
    private javax.swing.JMenu jMenuSalir;
    private javax.swing.JToolBar jToolBarButtons;
    // End of variables declaration//GEN-END:variables
}
